spring.application.name=EcomProject
spring.datasource.url=jdbc:mysql://localhost:3306/ecomdb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
# JSON output ke liye global format
spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=GMT+5:30